version: '3.1'

services:
  pulsar-standalone:
    image: apachepulsar/pulsar:2.8.1
    container_name: pulsar-standalone
    ports:
      - 8080:8080
      - 6650:6650
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: /bin/bash -c "bin/pulsar standalone"

volumes:
  pulsardata:
  pulsarconf: